#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nextCloudAndroid.Resource", IsApplication=true)]

namespace nextCloudAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int menu = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000d
			public const int bright_blue = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int custom_black = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int dark_red = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int dark_red_pressed = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int lightgraybackground = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int list_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int list_background_pressed = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int list_divider = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int list_item_title = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int selection_background_color = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int solid_blue = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int solid_green = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int solid_red = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int solid_yellow = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int whitesmoke = 2131034124;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int action_bar_height = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_btn_plus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_item_plus = 2130837505;
			
			// aapt resource value: 0x7f020040
			public const int blue = 2130837568;
			
			// aapt resource value: 0x7f020002
			public const int borderless_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_plus_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_plus_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_border = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int filepicker_file = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int filepicker_folder = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int filepicker_new_folder = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int filepicker_previous = 2130837514;
			
			// aapt resource value: 0x7f020041
			public const int green = 2130837569;
			
			// aapt resource value: 0x7f02000b
			public const int group_top = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_search = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_doc = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_drawer = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_espace = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_folder = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_join = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_move = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_music = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_options = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_photo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_rename = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_settings = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_trash = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_video = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int item_background = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int item_doc = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int item_fichier = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int item_folder = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int item_img = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int item_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int item_pdf = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int item_plus_normal = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int item_plus_pressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int item_ppt = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int item_pressed = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int item_rar = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int item_son = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int item_txt = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int item_vid = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int item_xls = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int item_zip = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int list_item_bg_normal = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int list_item_bg_pressed = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int list_selector = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int mesdocuments_icon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int mesdocuments_logo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int mesphotos_icon = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int mesphotos_logo = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int messons_icon = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int messons_logo = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int mesvideos_icon = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int mesvideos_logo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int monoandroidsplash = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int nc_logo = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int nextCloud = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int nextdoc_icon = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int option_item_bg = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int option_item_normal = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int option_item_pressed = 2130837565;
			
			// aapt resource value: 0x7f02003f
			public const int red = 2130837567;
			
			// aapt resource value: 0x7f020044
			public const int screen_background_black = 2130837572;
			
			// aapt resource value: 0x7f02003e
			public const int search_icon = 2130837566;
			
			// aapt resource value: 0x7f020045
			public const int translucent_background = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int transparent_background = 2130837574;
			
			// aapt resource value: 0x7f020043
			public const int white = 2130837571;
			
			// aapt resource value: 0x7f020042
			public const int yellow = 2130837570;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b003b
			public const int Applogo = 2131427387;
			
			// aapt resource value: 0x7f0b002f
			public const int FileDateCreated = 2131427375;
			
			// aapt resource value: 0x7f0b002e
			public const int FileName = 2131427374;
			
			// aapt resource value: 0x7f0b0016
			public const int ListViewFiles = 2131427350;
			
			// aapt resource value: 0x7f0b002d
			public const int Thumbnail = 2131427373;
			
			// aapt resource value: 0x7f0b004d
			public const int action_search = 2131427405;
			
			// aapt resource value: 0x7f0b0005
			public const int btnCancel = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int btnConfirm = 2131427334;
			
			// aapt resource value: 0x7f0b000b
			public const int btnCreateFolder2 = 2131427339;
			
			// aapt resource value: 0x7f0b0008
			public const int btnNavUp = 2131427336;
			
			// aapt resource value: 0x7f0b0047
			public const int btn_connect = 2131427399;
			
			// aapt resource value: 0x7f0b003e
			public const int btnlogin = 2131427390;
			
			// aapt resource value: 0x7f0b0040
			public const int btnsignup = 2131427392;
			
			// aapt resource value: 0x7f0b004b
			public const int content_frame = 2131427403;
			
			// aapt resource value: 0x7f0b0032
			public const int delete_item = 2131427378;
			
			// aapt resource value: 0x7f0b0007
			public const int directoryInfo = 2131427335;
			
			// aapt resource value: 0x7f0b000d
			public const int directoryList = 2131427341;
			
			// aapt resource value: 0x7f0b000c
			public const int divider = 2131427340;
			
			// aapt resource value: 0x7f0b0045
			public const int emailField = 2131427397;
			
			// aapt resource value: 0x7f0b000e
			public const int file_picker_image = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int file_picker_text = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int filepicker_main = 2131427344;
			
			// aapt resource value: 0x7f0b004e
			public const int filepicker_new_folder_item = 2131427406;
			
			// aapt resource value: 0x7f0b0002
			public const int folderName = 2131427330;
			
			// aapt resource value: 0x7f0b0021
			public const int folder_logo = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public const int folder_text = 2131427362;
			
			// aapt resource value: 0x7f0b0023
			public const int folderonly_text = 2131427363;
			
			// aapt resource value: 0x7f0b0003
			public const int footer = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int horizontalDivider = 2131427332;
			
			// aapt resource value: 0x7f0b0000
			public const int icon = 2131427328;
			
			// aapt resource value: 0x7f0b0030
			public const int icon_options = 2131427376;
			
			// aapt resource value: 0x7f0b001d
			public const int import_file_layout = 2131427357;
			
			// aapt resource value: 0x7f0b0012
			public const int info_text = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int lay_btns = 2131427347;
			
			// aapt resource value: 0x7f0b004c
			public const int leftListView = 2131427404;
			
			// aapt resource value: 0x7f0b0020
			public const int loading_files = 2131427360;
			
			// aapt resource value: 0x7f0b001b
			public const int logo_folder = 2131427355;
			
			// aapt resource value: 0x7f0b001e
			public const int logo_join = 2131427358;
			
			// aapt resource value: 0x7f0b0017
			public const int mesdocuments_logo = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int mesdocuments_text = 2131427352;
			
			// aapt resource value: 0x7f0b0025
			public const int mesphotos_logo = 2131427365;
			
			// aapt resource value: 0x7f0b0026
			public const int mesphotos_text = 2131427366;
			
			// aapt resource value: 0x7f0b0029
			public const int messons_logo = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public const int messons_text = 2131427370;
			
			// aapt resource value: 0x7f0b002b
			public const int mesvideos_logo = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public const int mesvideos_text = 2131427372;
			
			// aapt resource value: 0x7f0b0038
			public const int move_item = 2131427384;
			
			// aapt resource value: 0x7f0b0039
			public const int move_logo = 2131427385;
			
			// aapt resource value: 0x7f0b0048
			public const int mprogress = 2131427400;
			
			// aapt resource value: 0x7f0b004a
			public const int myDrawer = 2131427402;
			
			// aapt resource value: 0x7f0b003f
			public const int myProgress = 2131427391;
			
			// aapt resource value: 0x7f0b0011
			public const int nc_logo = 2131427345;
			
			// aapt resource value: 0x7f0b001a
			public const int new_folder_layout = 2131427354;
			
			// aapt resource value: 0x7f0b0014
			public const int newitem_btn = 2131427348;
			
			// aapt resource value: 0x7f0b0031
			public const int options_lay = 2131427377;
			
			// aapt resource value: 0x7f0b0044
			public const int passwordField = 2131427396;
			
			// aapt resource value: 0x7f0b0019
			public const int popup_new = 2131427353;
			
			// aapt resource value: 0x7f0b0049
			public const int progressBar1 = 2131427401;
			
			// aapt resource value: 0x7f0b003d
			public const int pwinput = 2131427389;
			
			// aapt resource value: 0x7f0b0041
			public const int relativeLayout1 = 2131427393;
			
			// aapt resource value: 0x7f0b0035
			public const int rename_item = 2131427381;
			
			// aapt resource value: 0x7f0b0036
			public const int rename_logo = 2131427382;
			
			// aapt resource value: 0x7f0b0043
			public const int requestFocus2 = 2131427395;
			
			// aapt resource value: 0x7f0b0027
			public const int search_logo = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int search_text = 2131427368;
			
			// aapt resource value: 0x7f0b0046
			public const int signupButton = 2131427398;
			
			// aapt resource value: 0x7f0b0015
			public const int spacefragment = 2131427349;
			
			// aapt resource value: 0x7f0b0001
			public const int title = 2131427329;
			
			// aapt resource value: 0x7f0b0033
			public const int trash_logo = 2131427379;
			
			// aapt resource value: 0x7f0b0024
			public const int txtLabel = 2131427364;
			
			// aapt resource value: 0x7f0b001c
			public const int txt_dossier = 2131427356;
			
			// aapt resource value: 0x7f0b001f
			public const int txt_join = 2131427359;
			
			// aapt resource value: 0x7f0b003a
			public const int txt_move = 2131427386;
			
			// aapt resource value: 0x7f0b0037
			public const int txt_renommer = 2131427383;
			
			// aapt resource value: 0x7f0b0034
			public const int txt_supprimer = 2131427380;
			
			// aapt resource value: 0x7f0b000a
			public const int txtvSelectedFolder = 2131427338;
			
			// aapt resource value: 0x7f0b0009
			public const int txtvSelectedFolderLabel = 2131427337;
			
			// aapt resource value: 0x7f0b0042
			public const int usernameField = 2131427394;
			
			// aapt resource value: 0x7f0b003c
			public const int usrinput = 2131427388;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int drawer_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int filepicker_createfolder = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int filepicker_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int filepicker_listitem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int filepicker_mainactivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FirstTimeMain = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_document = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_dossier = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_espace = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fragment_move = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fragment_parametre = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fragment_photo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int fragment_search = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int fragment_son = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int fragment_video = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ListItemRow = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LoginLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int RegisterLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TheMain = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int activity_main_actions = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int filepicker_menu = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int access_text = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int app_name = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int close_drawer = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int desc_list_item_icon = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int email_hint = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int filepicker_ApplicationName = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int filepicker_cancel_label = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int filepicker_confirm_label = 2131165207;
			
			// aapt resource value: 0x7f070020
			public const int filepicker_create_folder_error = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int filepicker_create_folder_error_already_exists = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int filepicker_create_folder_error_no_write_access = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int filepicker_create_folder_label = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int filepicker_create_folder_msg = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int filepicker_create_folder_success = 2131165213;
			
			// aapt resource value: 0x7f07001b
			public const int filepicker_enter_folder_msg = 2131165211;
			
			// aapt resource value: 0x7f070015
			public const int filepicker_ok = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int filepicker_selected_file_label = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int filepicker_selected_folder_label = 2131165208;
			
			// aapt resource value: 0x7f070021
			public const int filepicker_up_label = 2131165217;
			
			// aapt resource value: 0x7f07000b
			public const int input_empty = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int joinUs = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int login_button_label = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int login_error_message = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int login_error_title = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int logout_label = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int no_files_or_directories = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int open_drawer = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int password_hint = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int sign_up_button_label = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int sign_up_text = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int signup_error_message = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int signup_error_title = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int username_hint = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090002
			public const int Mono_Android_Theme_Splash = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int MyActionBar = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int nextCloudTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
